name: Run opentofu

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: fe9dcc0e-101c-4291-af95-2ccadd9e5346
          tenant-id: 4cda7170-067b-4002-af45-933da3207563
          subscription-id: 6507cd03-8896-4ac1-b320-b291724179c4
      
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.5

      - name: OpenTofu Init
        working-directory: ./tofu
        run: tofu init

      - name: OpenTofu Plan
        working-directory: ./tofu
        run: tofu plan -out=tfplan

      - name: OpenTofu Apply
        working-directory: ./tofu
        run: tofu apply tfplan
